# Generated by Django 4.2 on 2023-07-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_state_order_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
