# Generated by Django 4.2.1 on 2023-07-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='address',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
