# Generated by Django 4.2.1 on 2023-07-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orderproduct_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('Razorpay', 'Razorpay')], default='cash', max_length=20),
        ),
    ]
