# Generated by Django 4.2.1 on 2023-07-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
