# Generated by Django 4.2.1 on 2023-07-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_order'),
        ('cart', '0008_orderproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.orders'),
        ),
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
    ]
