# Generated by Django 4.2.1 on 2023-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_orderproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
