# Generated by Django 4.2.1 on 2023-07-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_order'),
        ('cart', '0011_remove_orders_is_paid_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('pending', 'pending'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='New', max_length=255),
        ),
    ]
